from .location import RetinalFieldLocationTemplate, RelativeFieldLocationTemplate, \
    RetinalFieldLocationCatTemplate
from .optic_disk import OpticDiskTemplate
from .location_from_table import RetinalFieldLocationFromTableTemplate, RetinalFieldLocationTableParamsTemplate
from .roi_location import RelativeRoiLocationWrtFieldTemplate, RelativeRoiLocationTemplate, RetinalRoiLocationTemplate
from .outline import OutlineRelTemplate, OutlineAbsTemplate
